name: build

on:
  push:
  workflow_dispatch:

env:
  VERSION: "1.6.1"
  IMAGE: ghcr.io/emgag/prometheus-varnish-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to github docker registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: >
          docker buildx build --pull --push
          --build-arg VERSION=${{ env.VERSION }}
          -t ${{ env.IMAGE }}:${{ env.VERSION }}
          .
